/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegendsRouteImport } from './routes/legends'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as LegendsIndexRouteImport } from './routes/legends.index'
import { Route as StoriesNewRouteImport } from './routes/stories.new'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as LegendsNewRouteImport } from './routes/legends.new'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsRoute = LegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const LegendsIndexRoute = LegendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegendsRoute,
} as any)
const StoriesNewRoute = StoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesRoute,
} as any)
const LegendsNewRoute = LegendsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LegendsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/legends': typeof LegendsRouteWithChildren
  '/login': typeof LoginRoute
  '/schools': typeof SchoolsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/legends/new': typeof LegendsNewRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/legends/': typeof LegendsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/schools': typeof SchoolsRoute
  '/legends/new': typeof LegendsNewRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/legends': typeof LegendsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/legends': typeof LegendsRouteWithChildren
  '/login': typeof LoginRoute
  '/schools': typeof SchoolsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/legends/new': typeof LegendsNewRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/legends/': typeof LegendsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/legends'
    | '/login'
    | '/schools'
    | '/stories'
    | '/legends/new'
    | '/stories/$id'
    | '/stories/new'
    | '/legends/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/schools'
    | '/legends/new'
    | '/stories/$id'
    | '/stories/new'
    | '/legends'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/legends'
    | '/login'
    | '/schools'
    | '/stories'
    | '/legends/new'
    | '/stories/$id'
    | '/stories/new'
    | '/legends/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LegendsRoute: typeof LegendsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SchoolsRoute: typeof SchoolsRoute
  StoriesRoute: typeof StoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends': {
      id: '/legends'
      path: '/legends'
      fullPath: '/legends'
      preLoaderRoute: typeof LegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/legends/': {
      id: '/legends/'
      path: '/'
      fullPath: '/legends/'
      preLoaderRoute: typeof LegendsIndexRouteImport
      parentRoute: typeof LegendsRoute
    }
    '/stories/new': {
      id: '/stories/new'
      path: '/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof StoriesNewRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/legends/new': {
      id: '/legends/new'
      path: '/new'
      fullPath: '/legends/new'
      preLoaderRoute: typeof LegendsNewRouteImport
      parentRoute: typeof LegendsRoute
    }
  }
}

interface LegendsRouteChildren {
  LegendsNewRoute: typeof LegendsNewRoute
  LegendsIndexRoute: typeof LegendsIndexRoute
}

const LegendsRouteChildren: LegendsRouteChildren = {
  LegendsNewRoute: LegendsNewRoute,
  LegendsIndexRoute: LegendsIndexRoute,
}

const LegendsRouteWithChildren =
  LegendsRoute._addFileChildren(LegendsRouteChildren)

interface StoriesRouteChildren {
  StoriesIdRoute: typeof StoriesIdRoute
  StoriesNewRoute: typeof StoriesNewRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesIdRoute: StoriesIdRoute,
  StoriesNewRoute: StoriesNewRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LegendsRoute: LegendsRouteWithChildren,
  LoginRoute: LoginRoute,
  SchoolsRoute: SchoolsRoute,
  StoriesRoute: StoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
